import type { Maybe } from 'src/types/index.ts'
import { CodeBuffer } from 'src/utils/CodeBuffer.ts'
import { escapeJSKey } from 'src/utils/escapeJSKey.ts'
import type { ComfySchema } from 'src/sdk-generator/ComfySchema.ts'

import { type ComfyNodeSchema, wrapQuote } from 'src/sdk-generator/ComfyNodeSchema.ts'

/**
 * convert a host id to the namespace name it gets inside the global `Comfy` namespace
 * e.g. 'windows-1' -> 'Windows1', 'my_cloud.instance' -> 'MyCloudInstance'
 */
export function hostIdToNamespace(hostId: string): string {
   const parts = hostId.split(/[^a-zA-Z0-9]+/).filter(Boolean)
   const ns = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
   if (ns.length === 0) throw new Error(`cannot derive a namespace from host id "${hostId}"`)
   // namespaces can't start with a digit
   return /^[0-9]/.test(ns) ? `Host${ns}` : ns
}

export type CodegenOptions = {
   /** host id; drives both the `Comfy.Hosts` registry key and the namespace name */
   hostId: string
   /** module to import runtime-facing types from (default: 'comfy-ts') */
   packageName?: string
}

/**
 * emit the typed SDK for one host:
 *
 *    declare global {
 *       namespace Comfy {
 *          namespace <HostNs> { IN / OUT / Node / Builder / Slots / Accepts / Union / ... }
 *          interface Hosts { '<host-id>': <HostNs>.Sdk }
 *       }
 *    }
 */
export function codegenSDK(this: ComfySchema, opts: CodegenOptions): string {
   const ns = hostIdToNamespace(opts.hostId)
   const packageName = opts.packageName ?? 'comfy-ts'
   const b = new CodeBuffer()
   const p = b.w

   p(`/** generated by comfy-ts for host "${opts.hostId}" — do not edit */`)
   p(``)
   p(`import type { ComfyNode, ComfyNodeOutput, ComfyNodeMetadata, ComfyNodeSchemaJSON } from '${packageName}'`)
   p(``)
   p(`declare global {`)
   b.indent()

   p(`namespace Comfy {`)
   b.indent()

   p(`namespace ${ns} {`)
   b.indent()

   // #region PythonModules ----------------------------------------------------------------------
   p(`// #${''}region PythonModules`)
   p(`/** list of all python modules installed on this host */`)
   p(`export type PythonModules =`)
   b.indent()
   const pythonModulesArr: [string, string[]][] = Array.from(this.pythonModules.entries()) //
      .toSorted((a, b) => a[0].localeCompare(b[0]))
   for (const [k, v] of pythonModulesArr) {
      p(`/**`)
      p(`* Nodes: ${v.join(', ')}`)
      p(`*/`)
      p(`| ${wrapQuote(k)}`)
   }
   b.deindent()
   p(`// #${''}endregion`)

   // #region IN ---------------------------------------------------------------------------------
   const nodes = this.nodes.toSorted((a, b) => a.nodeKey.localeCompare(b.nodeKey))
   p(`interface IN {`)
   b.indent()
   for (const n of nodes) {
      p(`${escapeJSKey(n.nodeKey)}: {`)
      for (const i of n.inputs) {
         const opts_ = typeof i.opts === 'string' ? null : i.opts
         let type = `Accepts[${JSON.stringify(i.typeName)}]`
         // COMBO inputs (ComfyUI ≥ 0.3.x) carry literal choices in opts.options
         const comboOptions =
            i.typeName === 'COMBO' && Array.isArray(opts_?.options)
               ? opts_.options.filter(
                    (o): o is string | number | boolean =>
                       typeof o === 'string' || typeof o === 'number' || typeof o === 'boolean',
                 )
               : []
         if (comboOptions.length > 0) {
            type = `${comboOptions.map((o) => JSON.stringify(o)).join(' | ')} | ${type}`
         }
         // custom text/primitive widget types (placeholder/multiline/default in opts)
         // also accept the raw literal, e.g. AUTOCOMPLETE_TEXT_LORAS is just a string
         else if (opts_ && !i.isPrimitive && !i.isEnum) {
            if (typeof opts_.default === 'string' || opts_.placeholder != null || opts_.multiline != null) {
               type = `string | ${type}`
            } else if (typeof opts_.default === 'number') {
               type = `number | ${type}`
            } else if (typeof opts_.default === 'boolean') {
               type = `boolean | ${type}`
            }
         }
         if (opts_) {
            const rendered = n.renderOpts(opts_)
            if (rendered) p(`    ${rendered}`)
         }
         const canBeOmmited = opts_?.default !== undefined || !i.required
         p(`    ${i.nameInComfyEscaped}${canBeOmmited ? '?' : ''}: ${type}`)
      }
      p(`},`)
   }
   b.deindent()
   p('}')
   p('')

   // #region OUT --------------------------------------------------------------------------------
   p(`interface OUT {`)
   b.indent()
   for (const n of nodes) {
      p(`${escapeJSKey(n.nodeKey)}: {`)
      n.outputs.forEach((i, ix) => {
         p(`   ${escapeJSKey(i.outKey)}: ComfyNodeOutput<'${i.typeName}', ${ix}>,`)
      })
      p(`}`)
   }
   b.deindent()
   p('}')

   // #region Node -------------------------------------------------------------------------------
   p(`interface Node {`)
   for (const n of nodes) {
      p(
         `   ${escapeJSKey(n.nodeKey)}: ComfyNode<IN[${JSON.stringify(n.nodeKey)}], OUT[${JSON.stringify(n.nodeKey)}]> & {`,
      )
      for (const hassingle of n.singleOutputs) {
         p(`      ${escapeJSKey(`_${hassingle.typeName}`)}: ComfyNodeOutput<'${hassingle.typeName}'>`)
      }
      p(`   }`)
   }
   p('}')

   // #region Builder ----------------------------------------------------------------------------
   p(`interface Builder {`)
   for (const n of nodes) {
      const baseDescription = `displayName="${n.raw.display_name}" category="${n.category}" name="${n.nameInComfy}" output=[${n.outputs.map((o) => o.outKey).join(', ')}]`
      if (n.raw.description) {
         p(`   /**`)
         p(
            n.raw.description
               .split('\n')
               .map((i) => `    * ${i}`)
               .join('\n'),
         )
         p(`    * ${baseDescription}`)
         p(`   **/`)
      } else {
         p(`    /** ${baseDescription} */`)
      }
      p(
         `   ${escapeJSKey(n.nodeKey)}(p: IN[${JSON.stringify(n.nodeKey)}], meta?: ComfyNodeMetadata): Node[${JSON.stringify(n.nodeKey)}]`,
      )
   }
   p(`}`)

   // #region Slots ------------------------------------------------------------------------------
   p(`interface Slots {`)
   for (const e of this.knownUnionByHash.values()) {
      p('   // ' + e.unionName)
      for (const alias of e.enumNames) {
         p(`   ${escapeJSKey(alias)}: Union['${e.unionName}']`)
      }
   }
   p(`}`)

   // #region Embeddings -------------------------------------------------------------------------
   p(`type Embeddings = ${this.data.embeddings.map((e) => wrapQuote(e)).join(' | ') || '""'}`)

   const slotTypes = [...this.knownSlotTypes.values()] //
      .map((comfyType) => ({
         comfyType,
         tsType: this.toTSType(comfyType),
         tsType2: this.toAcceptsType(comfyType),
      }))
      .sort((a, b) => b.tsType.length - a.tsType.length)

   // #region Producer ---------------------------------------------------------------------------
   p('')
   p('interface Producer {')
   b.indent()
   for (const tp of slotTypes) {
      const allProducingNodes: Maybe<ComfyNodeSchema[]> = this.nodesByProduction[tp.comfyType]
      if (allProducingNodes) {
         p(`${escapeJSKey(tp.comfyType)}: Pick<Builder, ${allProducingNodes.map((i) => `'${i.nodeKey}'`).join(' | ')}>`)
      } else {
         p(`${escapeJSKey(tp.comfyType)}: {}, // no node can output this type.`)
      }
   }
   b.deindent()
   p('}')

   // #region Accepts -----------------------------------------------------------------------------
   p(`interface Accepts {`)
   b.indent()
   // 1/3
   p('// injected bottom type (broken/null input specs land here)')
   p(`INVALID_null: any`)

   // 2/3
   p('')
   p('// named slot types: everything an input of that type accepts')
   for (const t of slotTypes) {
      p(
         `${escapeJSKey(t.comfyType)}: ${t.tsType} | HasSingle['${t.comfyType}'] | ((x: Producer['${t.comfyType}']) => Accepts['${t.comfyType}'])`,
      )
   }

   // 3/3
   p('')
   p('// enum unions: literal values or an output carrying one')
   for (const t of this.knownUnionByHash.values()) {
      p(`${escapeJSKey(t.unionName)}: Union['${t.unionName}'] | ComfyNodeOutput<'${t.unionName}'>`)
   }
   b.deindent()
   p(`}\n`)

   // #region Union ------------------------------------------------------------------------------
   p('interface Union {')
   for (const e of this.knownUnionByHash.values()) {
      if (e.values.length > 0) {
         p(`   // ${JSON.stringify(e.enumNames)}`)
         p(`   ${e.unionName}: ${e.values.map((v) => `${JSON.stringify(v)}`).join(' | ')}`)
      } else {
         p(`    ${e.unionName}: '🔴' // never`)
      }
   }
   p('}')

   // #region HasSingle --------------------------------------------------------------------------
   p(`export interface HasSingle {`)
   for (const t of slotTypes) {
      p(`    ${escapeJSKey(t.comfyType)}: { '_${t.comfyType}': ${t.tsType} }`)
   }
   p(`}`)

   for (const t of this.enumsAppearingInOutput.values()) {
      p(`export interface HasSingle_${t} { _${t}: Union['${t}'] }`)
   }

   // #region Schemas ----------------------------------------------------------------------------
   p(`export type Schemas = { [k in NodeType]: ComfyNodeSchemaJSON }`)
   p(`export type NodeType = ${this.nodes.map((i) => `'${i.nodeKey}'`).join(' | ')}`)

   // #region Sdk --------------------------------------------------------------------------------
   p(``)
   p(`/** everything above, packaged for the Comfy.Hosts registry */`)
   p(`interface Sdk {`)
   p(`   IN: IN`)
   p(`   OUT: OUT`)
   p(`   Node: Node`)
   p(`   Builder: Builder`)
   p(`   Slots: Slots`)
   p(`   Accepts: Accepts`)
   p(`   Union: Union`)
   p(`   Producer: Producer`)
   p(`   Embeddings: Embeddings`)
   p(`   Schemas: Schemas`)
   p(`   NodeType: NodeType`)
   p(`}`)

   b.deindent()
   p(`}`) // end namespace <HostNs>

   p(``)
   p(`interface Hosts {`)
   p(`   ${wrapQuote(opts.hostId)}: ${ns}.Sdk`)
   p(`}`)

   b.deindent()
   p('}') // end namespace Comfy

   b.deindent()
   p('}') // end declare global
   p(``)
   p(`export {}`)

   return b.content
}
