// the web panel's favicon, derived from the project icon: a 64px png inlined as a data uri, so it
// ships inside the code and works the same from src and dist. Re-run when the icon changes.
// usage: bun scripts/gen-favicon.ts
import { writeFileSync } from 'node:fs'
import sharp from 'sharp'

const SOURCE = '.shipkit/identity/icon.png'
const OUT = 'src/cli/serve/favicon.ts'

const png = await sharp(SOURCE)
   .resize(64, 64, { fit: 'contain', kernel: 'lanczos3' })
   .png({ compressionLevel: 9 })
   .toBuffer()
writeFileSync(
   OUT,
   `// generated by scripts/gen-favicon.ts from ${SOURCE}, never edited by hand\nexport const FAVICON_DATA_URI = 'data:image/png;base64,${png.toString('base64')}'\n`,
)
console.log(`[favicon] 🟢 ${OUT} (${png.length} bytes)`)
