import { type } from 'arktype'
import { type ImageMeta, imageMeta } from 'image-meta'
import { basename } from 'pathe'
import type { Sharp } from 'sharp'
import { getComfyStorage } from 'src/storage/ComfyStorage.ts'
import { importSharp } from 'src/utils/lazySharp.ts'
import type { ComfyHost } from 'src/host/ComfyHost.ts'
import type { ComfyNodeMetadata } from 'src/graph/ComfyNodeID.ts'
import type { ComfyApiNodeJson } from 'src/sdk-generator/comfy-api-json.ts'
import type { AbsolutePath, Maybe } from 'src/types/index.ts'
import type { NodeOf } from 'src/types/comfy-sdk.ts'
import type { ComfyImageName } from 'src/sdk-generator/comfyui-types.ts'
import { bang } from 'src/utils/bang.ts'
import { hashArrayBuffer } from 'src/utils/hashArrayBuffer.ts'
import type { ComfyExecution } from 'src/runner/ComfyExecution.ts'
import type { ComfyWorkflow } from 'src/runner/ComfyWorkflow.ts'
import { type ComfyImageInfo, ComfyImageInfo_ark } from 'src/runner/ComfyWsApi.ts'

export type MediaImageData = {
   path: AbsolutePath

   // to avoid having to read the file if we already have the buffer around
   buffer?: Uint8Array

   // provenance ?
   execution?: ComfyExecution
   promptNodeID?: string | null

   comfyUIInfos?: ImageInfos_ComfyGenerated
}

export type ImageInfos_ComfyGenerated = {
   comfyHostHttpURL: string
   comfyImageInfo: ComfyImageInfo
}

export const ImageInfos_ComfyGenerated_ark = type({
   comfyHostHttpURL: 'string',
   comfyImageInfo: ComfyImageInfo_ark,
})

export class MediaImage {
   absPath: AbsolutePath

   /** the execution this image came from (null when not generated via comfy-ts) */
   execution: Maybe<ComfyExecution>

   /** return the workflow from which this image was generated */
   get workflow(): ComfyWorkflow | undefined {
      return this.execution?.workflow
   }

   promptNodeID: Maybe<string>

   constructor(data: MediaImageData) {
      this.absPath = data.path
      this.execution = data.execution
      this.promptNodeID = data.promptNodeID
      if (data.buffer != null) this.updateBuffer(data.buffer)
   }

   /** free-form labels; filled from ComfyNodeMetadata.tag(s) when generated via a prompt */
   tags: string[] = []

   /** the image as a Blob, e.g. to feed FormData uploads */
   getAsBlob(): Blob {
      return new Blob([this.buffer as Uint8Array<ArrayBuffer>], { type: `image/${this.metadata.type ?? 'png'}` })
   }

   /** return the image filename */
   get filename(): string {
      return basename(this.absPath)
   }

   get baseNameWithoutExtension(): string {
      const fname = this.filename
      return fname.slice(0, fname.lastIndexOf('.'))
   }

   /**
    * return file extension including dot
    * e.g. `.png`, or `.webp`
    * */
   get extension(): string {
      const fname = this.filename
      return fname.slice(((fname.lastIndexOf('.') - 1) >>> 0) + 1)
   }

   /** get the expected enum name (hash) */
   get enumName(): ComfyImageName {
      return `${this.hash}${this.extension}` as ComfyImageName
   }

   uploadAndReturnEnumName = async (host: ComfyHost): Promise<ComfyImageName> => {
      const finalName = await host.uploader.uploadImage(this, { type: 'input', override: true })
      return finalName
   }

   /** upload the media (hash-named, deduped) and load it in the given workflow as a `LoadImage` node */
   loadInWorkflow_viaLoadImageNode = async <WID extends string>(
      workflow: ComfyWorkflow<WID>,
   ): Promise<NodeOf<WID, 'LoadImage'>> => {
      const enumName = await this.uploadAndReturnEnumName(workflow.host)
      const img = bang(workflow.builderBase.LoadImage, 'host has no LoadImage node')({ image: enumName })
      // sanctioned cast: uploaded names are runtime-known; the node itself is the host's LoadImage
      return img as NodeOf<WID, 'LoadImage'>
   }

   /** load an image as mask in a comfy workflow beeing created */
   loadInWorkflowAsMask_viaLoadImageMask = async <WID extends string>(
      /** "alpha" | "blue" | "green" | "red" */
      channel: 'alpha' | 'blue' | 'green' | 'red',
      /** workflow to load image as mask into */
      workflow: ComfyWorkflow<WID>,
   ): Promise<NodeOf<WID, 'LoadImageMask'>> => {
      const enumName = await this.uploadAndReturnEnumName(workflow.host)
      const mask = bang(
         workflow.builderBase.LoadImageMask,
         'host has no LoadImageMask node',
      )({
         image: enumName,
         channel,
      })
      // sanctioned cast: same as above
      return mask as NodeOf<WID, 'LoadImageMask'>
   }

   /** return the json of the ComfyNode that led to this image */
   get ComfyNode(): Maybe<ComfyApiNodeJson> {
      const nodeID = this.promptNodeID
      if (nodeID == null) return null
      return this.workflow?.apiJson[nodeID]
   }

   /**
    * return the metadata of the ComfyNode that led to this image
    * null if not generated by comfy through a ComfyTS prompt
    * null if no metadata associated in the node in ComfyTS
    */
   get ComfyNodeMetadata(): Maybe<ComfyNodeMetadata> {
      const nodeID = this.promptNodeID
      if (nodeID == null) return null
      return this.workflow?.data.metadata[nodeID]
   }

   get width(): number | undefined {
      return this.metadata.width
   } // biome-ignore format: misc
   get height(): number | undefined {
      return this.metadata.height
   } // biome-ignore format: misc

   get width_orCrash(): number {
      return bang(this.metadata.width)
   } // biome-ignore format: misc
   get height_orCrash(): number {
      return bang(this.metadata.height)
   } // biome-ignore format: misc

   /**
    * return the base64 url for this file, regardless of it's exact representation
    * includes the prefix `data:image/<type>;base64,`
    */
   getBase64Url(): string {
      const imgType = this.metadata.type ?? 'png'
      return `data:image/${imgType};base64,${this.getBase64Payload()}`
   }

   /**
    * return the base64 url for this file, regardless of it's exact representation
    * does not includes the prefix `data:image/png;base64,`
    */
   getBase64Payload(): string {
      const bytes = this.buffer
      let bin = ''
      const chunk = 0x8000 // String.fromCharCode arg-count limit
      for (let i = 0; i < bytes.length; i += chunk) bin += String.fromCharCode(...bytes.subarray(i, i + chunk))
      return btoa(bin)
   }

   /** return the ArrayBuffer for this file, regardless it's exact representation  */

   /** lazilly loaded, call recomputeMetadata to expire */
   private _buffer: Maybe<Uint8Array> = null
   get buffer(): Uint8Array {
      if (this._buffer != null) return this._buffer
      this._buffer = getComfyStorage().readBytes(this.absPath)
      return this._buffer
   }
   freeBuffer = (): void => void (this._buffer = null)
   updateBuffer = (buff: Uint8Array): void => {
      this._buffer = buff
      this._metadata = null // expire metadata
      this._hash = null // expire hash
   }
   reloadBuffer = (): Uint8Array => {
      this._buffer = null // expire buffer
      this._metadata = null // expire metadata
      this._hash = null // expire hash
      return this.buffer
   }

   /** lazilly computed, call recomputeMetadata to expire */
   private _metadata: Maybe<ImageMeta> = null
   get metadata(): ImageMeta {
      if (this._metadata != null) return this._metadata
      this._metadata = imageMeta(this.buffer)
      return this._metadata
   }

   private _hash: Maybe<string> = null
   get hash(): string {
      if (this._hash != null) return this._hash
      this._hash = hashArrayBuffer(this.buffer)
      return this._hash
   }

   /**
    * Modify the image directly (inplace) by passing it though a `Sharp` pipeline
    * Sharp is a high performance image processing library.
    */
   processWithSharp_inplace = async (
      /** processing function */
      fn: (sharp: Sharp) => Sharp,
   ): Promise<this> => {
      const sharp = await importSharp('processWithSharp_inplace')
      const buff = await fn(sharp(this.buffer)).toBuffer()
      getComfyStorage().writeBytes(this.absPath, new Uint8Array(buff))
      this.updateBuffer(new Uint8Array(buff))
      return this
   }

   /**
    * Allow to run an image though some `Sharp` pipeline to produce an other image.
    * Sharp is a high performance image processing library.
    * to modify the image directly (inplace), use `processWithSharp_inplace` instead.
    */
   processWithSharp = async (
      /** processing function */
      fn: (sharp: Sharp) => Sharp,
      /** where to save the resulting image */
      path?: AbsolutePath,
   ): Promise<MediaImage> => {
      const sharp = await importSharp('processWithSharp')
      path ??= this.absPath + `.processed-${Date.now()}` + this.extension
      const buffer = new Uint8Array(await fn(sharp(this.buffer)).toBuffer())
      getComfyStorage().writeBytes(path, buffer)
      return new MediaImage({ path, buffer })
   }
}
